### ISSUE TITLE
Upgrading to 3.0 {"message":"Unauthorized"}

### ISSUE THREAD

**Issue by sea3pea0** [hassio-addons/addon-grafana#53] opened 2019-11-04 15:45 UTC
# Problem/Motivation
When upgrading to 3.0, I get the login page of Grafana. After logging in I get {"message":"Unauthorized"}

## Expected behavior
According to the changelog, after upgrading login shouldn't be necessary since grafana is now accessed by ingress.

## Actual behavior
When I click open in web ui, I'm taken to the grafana login page. After logging in with the user I created in grafana I am taken to a page that says: {"message":"Unauthorized"}

Am I doing something wrong? Should I do something with my user account in grafana before upgrading? I've went back to 2.3.0 and everything is working fine again. Please give some more details on the proper way to upgrade to 3.0. Thanks!

**Comment by frenck** [comment] 2019-11-04 16:14
Duplicate of #51

**Closed by frenck** 2019-11-04 16:14 UTC

**Comment by sea3pea0** [comment] 2019-11-04 17:16
my bad, should have searched closed issues. Thanks, got it sorted out from #51

**Comment by frenck** [comment] 2019-11-04 17:23
Don’t worry! Things happen! Glad you got it resolved 👍
