### ISSUE TITLE
Unable to connect to influxdb (local addon)

### ISSUE THREAD

**Issue by vandalon** [hassio-addons/addon-grafana#43] opened 2019-07-13 20:51 UTC
# Problem/Motivation
I can not connect to influxdb (also addon) whatever I try.

I'm sure that the influx credentials are ok, i used influx commandline tool from another box and that works perfectly. 

## Expected behavior

> (What you expected to happen)

## Actual behavior

i'm getting a conenction error and this shows up in the logs:
```
t=2019-07-13T22:48:16+0200 lvl=eror msg="Basic auth failed" logger=context error="User not found"
t=2019-07-13T22:48:16+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/query status=401 remote_addr=192.168.1.42 time_ms=0 size=31 referer=https://hass.wiebel.nl:3000/datasources/edit/1/
```

## Steps to reproduce

just install grafana and influx add on hassio, create a database and a user and try to connect to influx within grafana. 

any help would be greatly appreciated, i'm sure i'm missing something...

**Comment by frenck** [comment] 2019-07-26 15:31
Please share reproduction steps.
Only thing I can do with this information is pointing you to the manual or start throwing random things.

**Comment by timvy** [comment] 2019-08-12 11:41
Hi, I had the same problem, but clearing the cache of the browser you are connecting to grafana with, solved it for me.

**Comment by frenck** [comment] 2019-08-12 12:13
Thanks for sharing @timvy.

Since the original author of this issue failed to respond, I'll close this one up.

**Closed by frenck** 2019-08-12 12:13 UTC
