### ISSUE TITLE
Show in sidebar

### ISSUE THREAD

**Issue by ezar** [hassio-addons/addon-grafana#37] opened 2019-06-02 08:49 UTC
Please add option to show grafana in sidebar :)
Regards,

**Comment by frenck** [comment] 2019-06-02 09:43
Duplicate of #32 & #34.

Also in the documentation: https://github.com/hassio-addons/addon-grafana#known-issues-and-limitations (3e bullet point).

**Closed by frenck** 2019-06-02 09:43 UTC
