### ISSUE TITLE
Anonymous login not working, Grafan add-on 3.0.0

### ISSUE THREAD

**Issue by KBJM** [hassio-addons/addon-grafana#55] opened 2019-11-06 07:52 UTC
# Problem/Motivation
Anonymous login not working.
The problem started with the new authentication "ingress".
I have a number of weblinks in lovelace cards. In this example "Temperatur".
![image](https://user-images.githubusercontent.com/32913592/68278480-b2d79a00-0071-11ea-8d06-059137431b9b.png)
The url is: "http://192.168.1.xxx:8123/api/hassio_ingress/D9Thc-oHO7QXwg-rnlpHSNNptEbOxVZql9YXsSkn6A8/d/uD1_YkKZz/utetemperatur?orgId=1&kiosk=tv&panelId=2&fullscreen&from=now-24h&to=now", i get the following in the browser: "401: Unauthorized".
## Expected behavior
The Grafan panel should open without any error message.
## Actual behavior
Grafana config:
![image](https://user-images.githubusercontent.com/32913592/68278643-16fa5e00-0072-11ea-9c67-143c35c857e2.png)

Grafana add-on logg, part of it:
![image](https://user-images.githubusercontent.com/32913592/68278688-2aa5c480-0072-11ea-951a-e7fb0848b37a.png)

## Steps to reproduce
See above.

**Comment by frenck** [comment] 2019-11-06 21:23
If you open that URL in the browser directly it works?

**Comment by Lipown** [comment] 2019-11-06 22:28
Same issue here.

**Comment by L2v2P** [comment] 2019-11-07 06:11
I can confirm the same seems to apply to iframes in lovelace: 
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/26650432/68363899-9f3d3980-012c-11ea-84e2-a81d9588e18a.png">

Replacing the hassio.local domain by the IP address didn't solve the issue for me as this is the link I use:
`http://192.168.2.54:8123/api/hassio_ingress/gr7ojbhWongqOKsfOL9Ff8eGGjRslprMZIPKtRutWIw/d-solo/Sq35p5kgz/hass-io?orgId=1&refresh=10s&panelId=2&from=now/d&to=now&theme=light`

If I open Grafana from within Hassio it temporarily solves the issue, but it always returns. When I have it solved on one device (e.g. laptop), it persists on another (e.g. phone).

In the system log I see the following (one line per iframed Grafana graph it seems):
`19-11-07 06:07:56 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None
19-11-07 06:07:56 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None
19-11-07 06:07:56 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None
19-11-07 06:07:56 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None
19-11-07 06:07:56 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None
19-11-07 06:07:56 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None
19-11-07 06:07:56 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None
19-11-07 06:07:56 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None
19-11-07 06:07:56 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None`

**Comment by Lipown** [comment] 2019-11-07 06:45
I just woke up. Its working ok on the host machine, but on the cell phone it againg says not authorized. Just before sleep it was working. Same behaviour as above post.

**Comment by naamah75** [comment] 2019-11-07 17:07
Same issue here, I can't login to Grafana from outside of my local newtork.

`t=2019-11-07T17:56:52+0100 lvl=eror msg="Anonymous access organization error: 'Main Org.': Organization not found"
t=2019-11-07T17:56:53+0100 lvl=eror msg="Anonymous access organization error: 'Main Org.': Organization not found"
t=2019-11-07T17:58:48+0100 lvl=eror msg="Anonymous access organization error: 'Main Org.': Organization not found"
t=2019-11-07T17:58:48+0100 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"`

When I try to login from the public network I get the login page, but I haven't setup any credentials, so... what is the login / password?

![image](https://user-images.githubusercontent.com/34965103/68410481-143e5c80-0189-11ea-8d5e-fe41664073f5.png)

Anyway... before upgrading to 3.0.0 I was able to define a custom port for my grafana server and to link directly to this page instead of loading into the iframe panel of HA. Now it's possible to do it?

**Comment by frenck** [comment] 2019-11-08 09:56
@naamah75 

> msg="Anonymous access organization error: 'Main Org.': Organization not found"

Please see #53 on that.

And no, you can't set a port, as written in the release notes of the latest add-on release.

**Comment by danipin** [comment] 2019-11-08 20:30
I confirm, I also have the same problem, to solve it momentarily I must first open the graphical dashboard and then the links to the panels are seen but after a while the problem returns

**Comment by naamah75** [comment] 2019-11-09 05:28
Thank @frenck , solved the login problem following the issue reported here [https://github.com/hassio-addons/addon-grafana/issues/53](url).

`    {
      "name": "GF_AUTH_ANONYMOUS_ORG_NAME",
      "value": "myorganization.org"
    }`

**Comment by clayhill** [comment] 2019-11-09 23:40
I have the same `401: Unauthorized` problem.
It looks like the connection does not reach Grafana but is declined at the hassio ingress (`No valid ingress session None`). Grafana does not log anything.

If I log in on Grafana via the HA side bar, accessing a Grafana url works until I log out again _and_ clear the browser cache or restart the browser. Sadly, I have no idea how the ingress sessions work or how logging in to Grafana would alter that behavior, so I currently cannot debug it further. Any suggestions?

**Comment by naamah75** [comment] 2019-11-10 04:30
@clayhill have you set the right organization in the Grafana preferences?

**Comment by dsasov88** [comment] 2019-11-10 09:10
> I have the same `401: Unauthorized` problem.
> It looks like the connection does not reach Grafana but is declined at the hassio ingress (`No valid ingress session None`). Grafana does not log anything.
> 

there is another issue for this https://github.com/hassio-addons/addon-grafana/issues/56

**Comment by Atalonica** [comment] 2019-11-10 12:53
The same problem happens to me, but when using the Android app (add to home screen). It dissapears when I open and close any integrated platform like "Grafana" or "Configurator" or "InfluxDB" from the sidebar. For me the Grafana addon reports multiple entries of this message:
`"t=2019-11-10T13:44:41+0100 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"`.

**Comment by clayhill** [comment] 2019-11-10 13:56
> @clayhill have you set the right organization in the Grafana preferences?

Yes, I triple-checked it, including in grafana.db. The connection does not reach Grafana, or at least there is no trace log of it.

**Comment by febalci** [comment] 2019-11-13 21:25
When using https://myserver.dyndns.org:8123/api/hassio_ingress/5NF1FFK8pcGq7JW7Qdd9VK1bVWHm9 i can see the result, no problems (reverse proxy). But when i use http://192.168.100.23:8123/api/hassio_ingress/5NF1FFK8pcGq7JW7Qdd9VK1bVWHm9 i get 401:Unauthorized.

**Comment by frenck** [comment] 2019-11-16 08:43
Good point @febalci! The URL has to match the domain you are currently using for the main interface (either IP or domain).

**Comment by didi767** [comment] 2019-11-23 19:03
> When using https://myserver.dyndns.org:8123/api/hassio_ingress/5NF1FFK8pcGq7JW7Qdd9VK1bVWHm9 i can see the result, no problems (reverse proxy). But when i use http://192.168.100.23:8123/api/hassio_ingress/5NF1FFK8pcGq7JW7Qdd9VK1bVWHm9 i get 401:Unauthorized.
> 
> EDIT: Nope, disappeared like @L2v2P situation.

Hi @febalci! For me it's exactly the opposite, It doesn't work with the IP but with the "FQDN".
the problem is that it doesn't work outside of the local network or the same browser session (if I open the link using incognito mode I get 401 autorization error, but from the same browser where I got the graph direct link it works).

https://xxxxxxxxxxxxx.duckdns.org:8123/api/hassio_ingress/-hwMAIKpws-9IEtFPY6EVINgszHhC2uiEnkLs42ifts/render/d-solo/nKYcVJJWk/temp?orgId=1&refresh=5m&from=1574362748464&to=1574535548464&panelId=4&width=1000&height=500&tz=America%2FLos_Angeles

did you manage to solve this issue?

Thanks,

**Comment by didi767** [comment] 2019-11-23 19:15
Another update:

I see in the trace logs:
t=2019-11-23T11:12:14-0800 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:80 protocol=http subUrl=/api/hassio_ingress/-hwMAIKpws-9IEtFPxxxxx socket=

my addon config is set to use ssl so why it's listening on port 80? and localhost? :/
{
  "plugins": [],
  "env_vars": [
    {
      "name": "GF_AUTH_ANONYMOUS_ORG_NAME",
      "value": "xxxxxxxx.duckdns.org"
    },
    {
      "name": "GF_SECURITY_ALLOW_EMBEDDING",
      "value": "true"
    },
    {
      "name": "GF_SECURITY_LOGIN_REMEMBER_DAYS",
      "value": "365"
    }
  ],
  "log_level": "trace",
  "ssl": true,**
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}

**Comment by jcwillox** [comment] 2019-11-27 04:49
So, I think I may know why this is happening.
When accessing an ingress page via home assistant (such as clicking grafana in the sidebar) the browser makes a request to `https://myserver.dyndns.org:8123/api/hassio/ingress/session` this will create the ingress session, it will then load `https://myserver.dyndns.org:8123/api/hassio_ingress/5NF1FFK8pcGq7JW7Qdd9VK1bVWHm9`. 
If no ingress session has been created yet and you try to access that second URL it will fail with 401.
The second URL is a direct link to the grafana addon, but requires a valid ingress session to access, that session is only created when you click "open web ui" via the sidebar or addon page. Also, the ingress session cookie is deleted when you close your browser.

So anonymous auth and iframes won't work unless you create that ingress session first, which requires you to be authenticated with home assistant first. Not sure there's much we can do about this? Unless we can find a way to directly access grafana without an ingress session? 😕

This is also related to #56

**Comment by KBJM** [comment] 2019-11-27 08:42
I think this is a step back when it comes to anonymous auth. I have a couple of Grafana panels in HADashboard on a Raspberry PI with touch screen and now i can not access them. I hope "HA-team" will find a solution.

**Comment by marcstone-be** [comment] 2019-11-27 11:35
Yes, same issue here. I'm wondering why there's such a small number of people complaining about this? Would this only occur under certain circumstances?

**Comment by ggurrag** [comment] 2019-11-28 07:53
Same issue here.
Iframe: 401 Unauthorized.
Syslog: [hassio.api.ingress] No valid ingress session None

**Comment by febalci** [comment] 2019-11-28 08:04
> So, I think I may know why this is happening.
> When accessing an ingress page via home assistant (such as clicking grafana in the sidebar) the browser makes a request to `https://myserver.dyndns.org:8123/api/hassio/ingress/session` this will create the ingress session, it will then load `https://myserver.dyndns.org:8123/api/hassio_ingress/5NF1FFK8pcGq7JW7Qdd9VK1bVWHm9`.
> If no ingress session has been created yet and you try to access that second URL it will fail with 401.

@jcwillox Perfect Find! Without garafana opened first in hassio, the ingress request is missing the "ingress_session" id in the cookie. After opening grafana in hassio on some other tab, the same address request incorporates the missing "ingress_session" id, as example:
```
ingress_session=f80f9e2a291e6bfb18f77db4b1d7377f38eafefa704c65a6326ba612c097387ee9b14f4010043784079c861cb946ec4f5a7a49880aa43b252c8f3aad806d327e
```

**Comment by cheelio** [comment] 2019-12-03 20:49
> Yes, same issue here. I'm wondering why there's such a small number of people complaining about this? Would this only occur under certain circumstances?

I guess most people use the default hassio generated link instead of direct (deep-)linking to grafana panels.  But also for me, after adding ingress support, this addon became useless for me.

**Comment by petait** [comment] 2019-12-09 19:01
Having the same problem...

**Comment by edterbak** [comment] 2019-12-10 19:15
Me 2. 
Anything I can do to contribute? Logs, test, etc.?
HASS.IO on VM here, so its relative easy testing.

**Comment by IsaTTeN** [comment] 2019-12-12 18:18
I have the same problem... 401: Unauthorized all the time

**Comment by SweVictor** [comment] 2019-12-15 12:03
> I guess most people use the default hassio generated link instead of direct (deep-)linking to grafana panels. But also for me, after adding ingress support, this addon became useless for me.

Same problem for me, good to get verified it's not just me. Above sounds interesting - is there an alternate URL that would work on a HassIO installation? One where I could replace `https://host:port/api/hassio_ingress/[long-hash]/d-solo/[short-hash]/` with something that would respect the allow-anonymous setting? 

I very much prefer the Iframe solution since the graphs are interactive, I would however not like all members of the household to have access to the full Grafana interface for ... well ... obvious reasons 😄 

/Victor

**Comment by nullnullnul** [comment] 2019-12-21 07:05
This can't be the desired outcome of the change. I'm facing exactly similar symptoms, where now one of the core functionalities of my Home Assistant has been disabled, the monitoring capability. Where are the people who support for current configuration?

**Comment by edterbak** [comment] 2019-12-21 17:46
https://community.home-assistant.io/t/401-unauthorized-iframe-card-of-grafana-not-working-on-the-www-local-network-ok/148017/18

Something needs to be changed on Grafana side it turns out. Nothing to be done about it from HA side.

**Comment by frenck** [comment] 2019-12-21 18:32
Incorrect @edterbak, the problem is that Ingress doesn't have to be authenticated, there is no guarantee it can access the add-on over Ingress. This is not a Grafana issue.

**Comment by edterbak** [comment] 2019-12-21 22:42
Ok. I dont understand what you are saying. What ingress is, where it applies in between HA / Grafana / InfluxDB, etc.. Its beyond my knowledge (which you probably noticed already. :) )
Is there anything I / we can do to help? Logs, test, or start raising an issue somewhere?

**Comment by frenck** [comment] 2019-12-22 10:33
@edterbak, sure, you can help. Go fix :wink:

**Comment by edterbak** [comment] 2019-12-22 16:30
@frenck Ghehehe...  "It lays before the hand"😄  Tell me how, and I'll do it.

**Comment by frenck** [comment] 2019-12-23 10:14
If I knew how it would be fixed by now :wink:

**Comment by sinclairpaul** [comment] 2020-01-05 13:38
Direct access is now available again in the latest release, closing.

**Closed by sinclairpaul** 2020-01-05 13:38 UTC

**Comment by clayhill** [comment] 2020-01-10 20:38
Can anyone explain how to enable direct access?
I've been looking at the code and it seems to be enabled when a port is configured, but I still get the same 401 unauthorised message and "No valid ingress session None" in hassio log.

**Comment by sinclairpaul** [comment] 2020-01-10 20:43
@clayhill I answered something similar on the forum's, its probably best to post there, rather than in Github.
https://community.home-assistant.io/t/community-hass-io-add-on-grafana/54674/199?u=sinclairpaul

**Comment by clayhill** [comment] 2020-01-10 20:46
@sinclairpaul sorry I hadn't checked the forum yet. I'll blame the lack of sleep 🙂
